trigger:
- none

variables:
  serviceConnection : 'sc-azure'
  appName: 'CarteCreditAPI01'
  containerRegistry: 'cartecredit.azurecr.io'
  acrServiceConnection : 'sc-acr'
  imageRepository: 'carteCredit'
  resourceGroup: 'rg-TP4'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage : 'Build' 
  displayName:  'Génération et push image'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job : 'Build'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: '$(acrServiceConnection)'
          repository: '$(imageRepository)'
          command: 'buildAndPush'
          Dockerfile: '$(dockerfilePath)'
          buildContext: '$(Build.SourcesDirectory)'
        displayName: 'Génération et push image dans registre de conteneurs'

   
- stage : 'DeployToDev' 
  displayName:  'Déploiment en Dev'
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: 'Build'
  jobs:
    - deployment : 'DeployToDev'
      environment: 'Dev'
      strategy:
        runOnce:
         deploy:
           steps:
           - task: AzureCLI@2
             inputs:
              azureSubscription: 'sc-azure'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az container create -g $(resourceGroup) --name $(appName) --image $(containerRegistry)/$(imageRepository):$(tag) --registry-password $(password) --registry-username $(username) --cpu 1 --memory 1
             displayName: 'Déploiement sur Azure Container Instance'
